### ISSUE TITLE
As a player I want to be able to upload an Animal

### ISSUE THREAD

**Issue by zhihongpang-umbc** [ZhihongPang/Pokemon530#12]

**Comment by vg16855** [comment]
Current status of issue: This issue will probably last until the next sprint due to the database and other things needing to be implemented first. Also, testing has been done with a smaller version of the database, and not the current one we have now. This will quickly be resolved in the next sprint via an admin page and the full implementation of account creation. There has been quite a bit of work done on this, we just need a bit more testing to merge the branch.

**Comment by zhihongpang-umbc** [comment]
#13 Animal Upload functionality is implemented, along with unit tests for the animal table in the database.
